### PR TITLE
Toggleable capability specifics table after the main table

### PR DESCRIPTION
**Pull request by Pendrokar**
As mentioned in #14 

Only xVASynth row filled.

Preview:
https://github.com/Pendrokar/open-tts-tracker/blob/patch-3/README.md#capability-specifics

### CODE REVIEW

**Comment by Pendrokar** [comment]
Does not seem like anyone will bother to Fork this Pull Request in order to fill a row unless they see it on `main`.

**Comment by Pendrokar** [comment]
Checked spaces for some info to fill the rows, but nothing more. If a cell has no _CUDA_ it means I found it quite fast, but could not check if CPU is near as fast.

**Comment by Vaibhavs10** [comment]
Nice work! @Pendrokar - Should we merge this, and then we can continue adding more deets to it?

**Comment by Pendrokar** [comment]
Well I'd still like someone to review the text such as the column names as well as the legend beneath the table. I may also have taken too many liberties with the crosses ❌ as I was only going by from what I saw in the HF Spaces.

**Comment by Pendrokar** [comment]
I don't know what changes needed to be made. 🤷‍♂️ If you see good as is, then merge it.

**Review by Vaibhavs10 — APPROVED** [review]
Looks good to me to merge!

**Pull request merged**
